import assert from 'node:assert/strict'
import {graphicsFixture} from './studio-graphics-fixture.mjs'
import {readFileSync} from 'node:fs'
import {runInNewContext} from 'node:vm'

const source=readFileSync(new URL('../js/app.js',import.meta.url),'utf8')
const commerce=source.slice(source.indexOf('function arRecordingPoster('),source.indexOf('function renderDetail('))
const handlers=new Map(),root={dataset:{},querySelector:()=>null,querySelectorAll:selector=>groups[selector]||[]}
const control=key=>({dataset:{arTime:key},attrs:{},setAttribute(name,value){this.attrs[name]=value},addEventListener(type,fn){handlers.set(this,fn)}})
const buttons=[control('solo'),control('duo')],prices=[{},{}],hours=[{},{},{}],minutes=[{}],links=[{},{},{}],formats=[{}]
const groups={'[data-ar-time]':buttons,'[data-ar-price]':prices,'[data-ar-hours]':hours,'[data-ar-minutes]':minutes,'[data-ar-price-link]':links,'[data-ar-format]':formats}
const context={EXTRA_RECORDING_OPTIONS:[],PRODUCTS:{solo:{normal:120000,resultVideo:'proof.mp4'},duo:{normal:160000,resultVideo:'duo.mp4'}},EVENTS:[],shortWon:n=>(n/10000)+'만원',escapeHtml:x=>x,AR_DETAIL_CONTENT:{solo:{poster:'proof.jpg'}},document:{querySelector:()=>root},img:(src,alt)=>`<img src="${src}" alt="${alt}">`,soloReviewCarousel:()=>'<section id="reviews">카카오톡으로 받은 후기 원문 그대로예요</section>',wistiaBeforeAfterSection:()=>'<section id="wistiaBeforeAfter"></section>',arCdRatioSection:()=>'<section id="arRatioExperience"></section>',productPackageOverview:()=>'<strong>녹음 60분</strong>',productComparisonSection:()=>'<section>위스티아의 장점</section>',arExpertStory:()=>'<section>사운드 완성</section>',faq:items=>items.map(([question,answer])=>`<details><summary>${question}</summary><p>${answer}</p></details>`).join(''),footer:()=>'<footer></footer>'}
runInNewContext(graphicsFixture(source)+source.slice(source.indexOf('const SOLO_STUDIO_PROCESS='),source.indexOf('const DUO_STUDIO_PROCESS=')),context)
runInNewContext(source.slice(source.indexOf('function detailStudioSteps('),source.indexOf('function processStudioMeta(')),context)
runInNewContext(source.slice(source.indexOf('function detailPointSection('),source.indexOf('function filmCommerceDetail(')),context)
runInNewContext(commerce,context)
const markup=context.arCommerceDetail(context.PRODUCTS.solo)
const duoMarkup=context.arCommerceDetail({resultVideo:'duo.mp4',normal:160000},'duo')
assert.match(duoMarkup,/href="\/event\/duo"/)
assert.match(duoMarkup,/160,000<small>원/)
assert.match(duoMarkup,/2인 · 2시간/)
assert.match(markup,/AR 축가 사전녹음/)
assert.match(markup,/120,000/)
assert.match(markup,/SOLO · 1인/)
assert.match(duoMarkup,/DUET · 2인/)
assert.match(markup,/1곡 · 1인 · 1시간/)
assert.doesNotMatch(markup,/인원 제한|arc-review-link/)
assert.ok(markup.indexOf('mas-information')<markup.indexOf('id="reviews"'))
assert.match(markup,/가사 영상 제작 필요하신가요/)
assert.match(markup,/mas-cut-poster/)
assert.doesNotMatch(markup,/arc-recording-photos/)
assert.match(markup,/좋은 구간을 이어 붙여요/)
assert.match(markup,/lyric-video-v2\.webp/)
assert.equal((markup.match(/<details>/g)||[]).length,6)
assert.equal((markup.match(/data-ar-consult/g)||[]).length,0)
assert.equal((markup.match(/<h1 /g)||[]).length,1)
assert.match(markup,/구간별 1:1 디렉팅/)
assert.doesNotMatch(markup,/무제한 녹음을 약속|만족도|trackContact|pf\.kakao\.com/)
for(const id of ['arcDetails','reviews','arcFaq','arcProcess','wistiaBeforeAfter','arRatioExperience'])assert.match(markup,new RegExp(`id="${id}"`))
context.initArCommerceDetail()
handlers.get(buttons[1])()
assert.equal(root.dataset.arProduct,'duo')
assert.equal(buttons[1].attrs['aria-pressed'],'true')
assert.equal(prices[0].textContent,'160,000')
assert.equal(hours[2].textContent,'2')
assert.equal(minutes[0].textContent,'120')
assert.equal(formats[0].textContent,'DUET(2인)')
assert.equal(links[0].href,'/event/duo')
handlers.get(buttons[0])()
assert.equal(prices[1].textContent,'120,000')
assert.equal(minutes[0].textContent,'60')
assert.equal(formats[0].textContent,'SOLO(1인)')
assert.equal(links[2].href,'/event/solo')
// New detail CTAs go to options first, modal confirmation remains unchanged
assert.match(source,/route\(\{scrollAnchor\}\);if\(consult\)jumpToInquiry\(\)/)
assert.match(source,/app.innerHTML=arCommerceDetail\(p,key\)/)
console.log('AR commerce content, options, section targets and existing consultation delegation passed')
