import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const source=read('js/app.js'),css=read('css/functional-card-clarity.css')
const home=source.split('\n').find(line=>line.includes('app.innerHTML=\'<div class="we-home"'))
assert.doesNotMatch(home,/we-lead|직접 부르는 축가부터/)
assert.match(source,/details=details.replace\('<p>어려운 구간은 나누어 녹음하고<br>1:1 디렉팅으로 차근차근 맞춰갑니다<\/p>',''\)/)
assert.match(source,/<figcaption class="ar-essential-line"><span class="ar-line-full">어려운 구간은 나누어 녹음하고 1:1 디렉팅으로 차근차근 맞춰갑니다/)
assert.match(css,/#arcRecording \.mas-cut-poster[^}]*stroke:currentColor!important/)
assert.match(source,/같은 멜로디의 키를 내 음역에 맞게 조절합니다/)
assert.match(source,/원래 키<\/b>/)
assert.match(source,/내 목소리에 맞춘 키<\/b>/)
assert.doesNotMatch(source,/영상 시작과 마지막에는<br>원하시는 문구도 추가 가능합니다/)
const notices=source.split('\n').find(line=>line.includes('return \'<section class="arc-section arc-notices mas-notices"'))
assert.doesNotMatch(notices,/mas-venue-note/)
assert.match(source,/function mobileArProcess\(key="solo"\)\{\s*const steps=detailStudioSteps\(key\)/)
assert.match(source,/story-process-folder home-process-folder" open>/)
assert.match(source,/mas-detailed-process story-process-cards/)
assert.match(css,/mas-intro:has\(\.mas-gallery\[data-mobile-gallery\]\)\{padding-top:32px!important/)
assert.match(css,/\.mas-gallery-caption\{\s*top:28px;left:20px/)
console.log('14 detail comments: readable diagrams, compact copy, caption clearance and full process restored: passed')
