import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const source=read('js/app.js'),css=read('css/functional-card-clarity.css'),index=read('index.html')
const homeStart=source.indexOf('function renderWeddingHome(){')
const home=source.slice(homeStart,source.indexOf('\nfunction ',homeStart+1))
assert.match(home,/const service=\(key,title,hook,photo,number\)/)
assert.match(home,/<p><strong>'\+hook\+'<\/strong><\/p>/)
assert.doesNotMatch(home,/내 목소리를 미리 녹음해|당일 축가를 더 안정적으로|하객들도 함께 즐기는 영상으로|궁금한 작업을 누르면/)
assert.match(home,/결혼식에서 직접 축가를 부른다면/)
assert.match(home,/우리 목소리로 축가 영상을 만든다면/)
assert.match(home,/POINT 01<\/span><h2>상품 소개/)
assert.match(home,/재생 버튼을 눌러 확인해 보세요/)
assert.match(home,/눌러서 확인해 보세요/)
assert.match(css,/\.we-service-link\{\s*display:inline-flex;align-items:center;justify-content:center/)
assert.match(css,/#homeServices \.we-section-tag\{\s*background:var\(--mono-black\)!important;color:var\(--mono-white\)!important;border:0!important;border-radius:8px/)
assert.match(css,/\.we-directions-copy\{\s*padding:28px 22px 30px/)
assert.match(css,/\.wordmark>span\{\s*display:flex;flex-direction:column;align-items:flex-start;font-size:18px/)
assert.match(css,/\.we-hero \.we-hero-grid\{padding:0\}/)
assert.match(css,/\.we-cases-guide\{[^}]*white-space:nowrap/)
assert.match(index,/js\/app.js\?v=20261010-detail-polish-11b/)
for(const route of ['detail/solo','detail/duo','detail/duet-film','contact','info/location'])assert.match(read(route+'.html'),/20261005-detail-comments14-1/)
console.log('Nine marked home requests: secondary copy removed, original hooks retained, point box, compact single line, centered buttons, compact header and safe spacing: passed')
