import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const source=readFileSync(new URL('../js/app.js',import.meta.url),'utf8')
const css=readFileSync(new URL('../css/home-form-refresh.css',import.meta.url),'utf8')
const index=readFileSync(new URL('../index.html',import.meta.url),'utf8')
const home=source.slice(source.indexOf('function renderWeddingHome('),source.indexOf('function renderWeddingHome(')+22000)
for(const text of ['POINT 01 · 상품 소개','POINT 02 · 가격 안내','POINT 03 · 실제 제작 영상','POINT 04 · 고객 후기','POINT 05 · 보컬 보정','POINT 06 · 제작 과정','POINT 07 · 자주 묻는 질문']) assert.ok(home.includes(text),text)
assert.ok(source.includes('POINT 08 · 오시는 길'))
assert.match(home,/we-product-number/)
assert.match(home,/we-service-copy/)
const homeEnd=home.indexOf('function ',30)
const homeOnly=homeEnd<0?home:home.slice(0,homeEnd)
for(const removed of ['기본 가격과 추가 옵션을 미리 확인하고 필요한 구성만 선택하세요','오시는 길과 주차 안내','we-final']) assert.ok(!homeOnly.includes(removed),removed)
assert.match(css,/#app \.we-home \.we-heading :is\(h2,p\).*text-align:center!important/)
assert.match(css,/#app \.we-home \.studio-address-city\{width:100%;text-align:center!important\}/)
assert.match(css,/body\[data-page=event\]/)
assert.match(css,/max-width:720px/)
assert.match(css,/\.booking-price-sidebar\{display:flex!important\}/)
assert.match(css,/\.consultation-step.*background:#fff!important/)
assert.match(index,/home-form-refresh\.css\?v=20261004-unified-commerce-1/)
assert.match(css,/\.we-service\{[^}]*border:1px solid #bdcad5[^}]*box-shadow:inset/,'both product cards retain a visible rim and raised depth')
assert.match(source,/id="consultForm"/)
const contact=readFileSync(new URL('../js/contact-form.js',import.meta.url),'utf8')
assert.ok(contact.includes('입력한 내용은 홈페이지 서버에 저장하거나 자동으로 전송하지 않습니다'))
const prerender=readFileSync(new URL('../scripts/prerender.mjs',import.meta.url),'utf8')
assert.ok(prerender.includes("['homeServices','homeCases','homeLocation','homeProcess']"),'linked home sections must resolve on refresh')
assert.ok(prerender.includes('page(`/section/${section}`, seo.home, {robots:\'noindex, follow\'})'))
console.log('Home POINT hierarchy, product numbers, requested removals and scoped local form styling passed')
