import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const source=read('js/app.js'),css=read('css/functional-card-clarity.css')
const ba=source.split('\n').find(line=>line.startsWith('function wistiaBeforeAfterSection('))
const home=source.split('\n').find(line=>line.includes('id="homeExpert"'))
const story=source.split('\n').find(line=>line.includes('return \'<section class="wistia-process-studio story-process-cards"'))
assert.match(ba,/<p data-solo-sub class="ba-essential">구간별 녹음, 자연스러운 보정<\/p>/)
assert.match(ba,/보정 전과 후는 <u class="wistia-emphasis-underline">같은 녹음본<\/u>입니다/)
assert.doesNotMatch(ba,/보컬 소스는/)
assert.match(ba,/wistiaBeforeAfterSection\(compact=false\)/)
assert.match(source,/wistiaBeforeAfterSection\(true\)/)
assert.match(source,/<u class="wistia-emphasis-underline">서울이 아닌 부천<\/u>에서 운영해 가격 부담을 낮췄습니다/)
assert.match(home,/<details class="story-process-folder home-process-folder" open>/)
assert.equal(home.match(/<summary>.*?<\/summary>/)[0],story.match(/<summary>.*?<\/summary>/)[0])
assert.match(home,/class="process-folder-content"><div class="we-craft-grid">/)
for(const title of ['구간별 녹음 · 1:1 디렉팅','수작업 음정·박자 보정','방송 음악 작업 엔지니어'])assert.ok(home.includes(title))
for(const photo of ['process-no-people/03.svg','process-no-people/05.svg','process-no-people/06.svg'])assert.ok(home.includes(photo))
assert.match(css,/\.ba-essential\{[^}]*white-space:nowrap/)
assert.match(css,/\.wistia-emphasis-underline\{[^}]*text-underline-offset:4px/)
assert.match(read('js/site-motion.js'),/document.querySelectorAll\('\.story-process-folder'\)/)
assert.match(read('css/detail-point-system.css'),/prefers-reduced-motion:reduce/)
assert.doesNotMatch(read('js/before-after.js'),/badgeText\.textContent|보컬 소스는/)
assert.match(read('index.html'),/before-after.js\?v=20261005-detail-comments14-1/)
console.log('Home underlines, essential one-line copy and original DUET folder component/content: passed')
