import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const app=read('js/app.js'), css=read('css/phone-capture-fixes.css')
const home=app.slice(app.indexOf('function renderWeddingHome'),app.indexOf('function renderWeddingHome')+11000)
assert.doesNotMatch(home,/we-hero-foot|나에게 맞는 축가 찾기|1곡 기준 · 1인 12만원|스토리형 · 2인 기본 35만원/)
assert.doesNotMatch(home,/cta\('문의 작성'|빠른 견적 ↗/)
assert.match(home,/we-product-number/)
assert.match(home,/<u class="wistia-emphasis-underline">서울이 아닌 부천<\/u>에서 운영해 가격 부담을 낮췄습니다/)
assert.match(home,/보컬 디렉팅·수작업 보정·믹싱·마스터링은 기본 구성에 포함합니다/)
assert.doesNotMatch(css,/#floatingPrice\{display:none\}|width:calc\(50% - 3px\)/)
assert.match(css,/#floatingKakao :is\(#floatingPrice,#floatingKakaoChat\)\{display:flex/)
assert.match(css,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/)
assert.match(css,/\.we-hero\{min-height:0;padding-bottom:16px\}/)
assert.match(css,/#homeServices\{padding-top:40px\}/)
assert.match(css,/\.we-location>p\{font-size:15px/)
assert.match(css,/\.we-location>p\{font-size:14px/)
assert.match(css,/\.mobile-story-film \.story-process-folder \.process-folder-content\{padding-top:16px\}/)
assert.match(css,/\.mobile-story-film \.story-process-folder \.story-process-grid\{margin-top:0\}/)
assert.ok(read('index.html').includes('js/app.js?v=20261006-studio-editorial-1'))
assert.ok(read('index.html').includes('css/phone-capture-fixes.css?v=20261004-home-followup-7-1'))
assert.doesNotMatch(read('index.html'),/id="floatingPrice"|src="js\/quick-estimate/)
console.log('Seven home follow-up requests, latest quick-estimate removal and scoped spacing passed')
