import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {runInNewContext} from 'node:vm'
const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8')
const source=read('js/app.js'),contact=read('js/contact-form.js'),css=read('css/inquiry-flow.css')
const context={window:{}}
runInNewContext(contact,context)
const api=context.window.WistiaContact
const quote={service:'AR 축가 사전녹음',summary:'AR · 13만원',text:'인사\n━━━━━\n• 최종 예상 가격 : 130,000원'}
const embedded=api.render(quote,{embedded:true})
assert.equal((embedded.match(/<h1/g)||[]).length,0)
assert.equal((embedded.match(/<form/g)||[]).length,1)
assert.match(embedded,/name="service" value="AR 축가 사전녹음" readonly/)
assert.match(embedded,/작성이 필요해요😭/)
assert.match(api.render(null,{embedded:true}),/name="service" value="상담 후 결정" readonly/)
assert.match(api.render(null,{embedded:true}),/class="contact-quote" hidden/)
const submitted=api.text({name:'검수',source:'인스타 광고',service:quote.service},quote)
assert.match(submitted,/성함 : 검수/)
assert.match(submitted,/최종 예상 가격 : 130,000원/)
assert.doesNotMatch(api.text({service:'상담 후 결정'},null),/가격|120,000/)
const sync=source.slice(source.indexOf('function refreshInquiryQuote(){'),source.indexOf('function jumpToInquiry(){'))
const preview={hidden:false,querySelector:()=>({textContent:''})},service={readOnly:true,value:''}
context.document={querySelectorAll:()=>[],querySelector:selector=>selector==='#contactInquiryForm'?({elements:[],querySelector:key=>key==='[name="service"]'?service:preview}):null}
api.syncQuote(quote);assert.equal(service.value,quote.service);assert.equal(preview.hidden,false)
api.syncQuote(null);assert.equal(service.value,'상담 후 결정');assert.equal(preview.hidden,true)
const state={inquiryUndecided:false,currentEventProduct:'solo',window:{WistiaContact:{syncQuote:()=>{}}},calculate:()=>({product:{title:'AR'},finalPrice:130000}),shortWon:()=> '13만원',consultationText:()=>submitted}
runInNewContext('let contactQuote;'+sync+';refreshInquiryQuote();this.quote=contactQuote',state)
assert.equal(state.quote.text,submitted)
state.inquiryUndecided=true;runInNewContext('refreshInquiryQuote();this.quote=contactQuote',state);assert.equal(state.quote,null)
assert.match(source,/function renderContactPage\(\)\{renderEvent\('solo','',true\)\}/)
const integrated=api.render(quote,{integrated:true})
assert.doesNotMatch(integrated,/<form|문의 양식 작성|contact-quote/)
assert.match(integrated,/02<\/span><h2[^>]+>이름 및 예식일 작성/)
assert.match(integrated,/name="service" type="hidden" value="AR 축가 사전녹음" readonly/)
assert.ok(integrated.indexOf('name="name"')<integrated.indexOf('name="eventDateMode"'))
assert.ok(integrated.indexOf('name="eventDateMode"')<integrated.indexOf('name="bookingDateMode"'))
assert.match(integrated,/카카오톡 채널/)
assert.match(integrated,/메타 광고/)
const rendered=source.slice(source.indexOf('function renderEvent('),source.indexOf('function refreshInquiryQuote('))
assert.equal((rendered.match(/<form /g)||[]).length,1)
assert.doesNotMatch(rendered,/data-inquiry-jump|inquiry-price-options|<details/)
assert.ok(rendered.indexOf('bookingBaseSection(key)')<rendered.indexOf('integrated:true'))
assert.ok(rendered.indexOf('integrated:true')<rendered.indexOf('optionsTitle'))
assert.doesNotMatch(rendered,/bookingReview|contactReview/)
assert.match(rendered,/form="contactInquiryForm" type="submit"/)
assert.match(rendered,/WistiaContact.submit\(\)/)
assert.match(source,/closest\('\[data-contact-fields\]'\)/)
assert.match(source,/WistiaContact.restore\(document.querySelector\('#contactInquiryForm'\),draft\)/)
assert.match(source,/refreshInquiryQuote\(\);const values=Object.fromEntries\(new FormData\(e.target\)\);copyConsultationAndShowDialog\(window.WistiaContact.text\(values,contactQuote\)\)/)
assert.match(source,/consult:\(\)=>jumpToInquiry\(\)/)
assert.match(css,/body.inquiry-visible \.booking-price-sidebar\{display:none!important\}/)
assert.match(css,/\.inquiry-price-options\[hidden\]/)
const home=source.slice(source.indexOf('function renderWeddingHome(){'),source.indexOf('function detailPriceData('))
assert.doesNotMatch(home,/AR 축가 준비|studioSculpture\('record'\)/)
assert.ok(home.indexOf('id="homeCases"')<home.indexOf('we-review-wrap'))
assert.ok(home.indexOf('we-review-wrap')<home.indexOf('id="homeSound"'))
assert.doesNotMatch(home,/4단계로 준비하는|id="homeProcess"/)
assert.match(source,/POINT 02|POINT '\+number/)
assert.match(source,/linearGradient id="arJoinedWave"/)
assert.match(css,/arc-recording-flow li:nth-child\(2\)/)
context.FormData=class {constructor(form){this.entries=form.data}[Symbol.iterator](){return this.entries[Symbol.iterator]()}}
const draftForm={elements:[],data:[['name','검수'],['source','메타 광고'],['service','AR 축가 사전녹음'],['quoteProduct','solo'],['arDuration','on'],['eventDateMode','unknown'],['timeStart','17:00']]}
const draft=api.snapshot(draftForm)
assert.equal(draft.name,'검수')
assert.equal(draft.timeStart,'17:00')
assert.equal(draft.quoteProduct,undefined,'restoring inquiry fields must not overwrite the newly selected product')
assert.equal(draft.arDuration,undefined,'restoring inquiry fields must not overwrite SOLO/DUET')
const reviewNode={innerHTML:''}
context.document={querySelectorAll:()=>[],querySelector:selector=>selector==='#contactInquiryForm'?draftForm:selector==='#contactReview'?reviewNode:null}
api.syncReview()
assert.match(reviewNode.innerHTML,/검수/)
assert.match(reviewNode.innerHTML,/메타 광고/)
draftForm.data[0][1]='<script>검수</script>'
api.syncReview()
assert.doesNotMatch(reviewNode.innerHTML,/<script>/)
assert.match(reviewNode.innerHTML,/&lt;script&gt;/)
const flowCss=read('css/consultation-flow.css')
assert.match(flowCss,/fieldset.contact-field\{border:0/)
assert.match(flowCss,/body.inquiry-visible \.consultation-flow \.booking-price-sidebar\{display:none!important\}/)
assert.match(flowCss,/consultation-gift-heading/)
assert.match(flowCss,/@media\(prefers-reduced-motion:reduce\)/)
console.log('Single-page inquiry, optional price, current quote, preserved draft, existing popup and requested home/detail changes passed')
