import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {runInNewContext} from 'node:vm'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const index=read('index.html'),app=read('js/app.js'),css=read('css/inquiry-actions.css')
assert.doesNotMatch(index,/id="floatingPrice"|src="js\/quick-estimate/)
assert.doesNotMatch(app,/data-quick-estimate|WistiaQuickEstimate|floatingPrice/)
assert.match(index,/inquiry-actions\.css\?v=20261011-detail-polish-13/)
assert.ok(index.indexOf('css/inquiry-actions.css')<index.indexOf('</head>'))
const ctx={window:{}}
runInNewContext(read('js/contact-form.js'),ctx)
const actions=ctx.window.WistiaContact.submit()
assert.equal((actions.match(/<button /g)||[]).length,1)
assert.equal((actions.match(/class="inquiry-direct"/g)||[]).length,1)
assert.match(actions,/href="https:\/\/pf.kakao.com\/_GbExjX\/chat" target="_blank" rel="noopener noreferrer"/)
assert.match(actions,/양식 없이 일단 상담하기/)
assert.match(actions,/type="submit"[^>]+aria-label="작성한 내용으로 카카오톡 문의하기"/)
assert.doesNotMatch(actions,/disabled|data-quick-estimate|onclick/)
const event=app.slice(app.indexOf('function renderEvent('),app.indexOf('function refreshInquiryQuote('))
assert.match(event,/const sidebar=priceSidebarSection\(\)/)
assert.match(event,/form="contactInquiryForm" type="submit"/)
assert.match(event,/sidebar\+'<\/div>'\+actions/)
assert.match(css,/\.inquiry-actions\{position:static/)
assert.doesNotMatch(css,/position:fixed|position:sticky/)
assert.doesNotMatch(index,/id="floatingKakao"|id="soloDesktopCta"/)
assert.match(app,/class="product-inquiry"/)
assert.match(css,/grid-template-columns:1fr/)
assert.match(css,/prefers-reduced-motion:reduce/)
assert.match(app,/validationIssues\(e.target\)[\s\S]*?if\(issues.length\)\{showContactValidationDialog\(issues\);return\}/)
console.log('Quick estimate unmounted, two ordinary inquiry actions, external native submit, validation and direct chat passed')
