import assert from 'node:assert/strict'
import {graphicsFixture} from './studio-graphics-fixture.mjs'
import {readFileSync,existsSync} from 'node:fs'
import {runInNewContext} from 'node:vm'
const read=file=>readFileSync(new URL('../'+file,import.meta.url),'utf8')
const source=read('js/app.js'),css=read('css/mobile-ar-solo.css'),home=read('css/mobile-studio-home.css'),shell=read('index.html')
let mobile=false
const scope={
 PRODUCTS:{solo:{normal:120000,resultVideo:'assets/video/groom-wedding-song-ar.mp4'},duo:{normal:160000,resultVideo:'assets/video/duo-wedding-song-ar.mp4'}},
 AR_DETAIL_CONTENT:{solo:{poster:'assets/img/ar-detail/solo-live-proof.jpg'}},
 img:(src,alt)=>'<img src="'+src+'" alt="'+alt+'">',escapeHtml:x=>x,
 EVENTS:[['discount',10000],['discount',10000],['payback',30000],['payback',10000],['payback',10000],['payback',10000]].map(([type,discount])=>({type,label:'참여 혜택',discount,detail:'승인된 조건'})),shortWon:n=>(n/10000)+'만원',
 soloReviewCarousel:()=>'<section id="reviews"><header><span data-solo-kicker>고객 후기</span><h2 id="soloReviewTitle">실제 고객 후기</h2><p data-solo-sub>직접 보내주신 카카오톡 후기 원문입니다</p></header></section>',
 productPackageOverview:()=>'<div>기본 구성</div>',productComparisonSection:()=>'<section>장점</section>',arExpertStory:()=>'<section>엔지니어</section>',
 faq:items=>items.map(([q,a])=>'<details><summary>'+q+'</summary><p>'+a+'</p></details>').join(''),footer:()=>'<footer></footer>',
 arCdRatioSection:()=>'<section id="arRatioExperience"><p class="wistia-ar__eyebrow">AR RATIO EXPERIENCE</p><h2>AR 비율</h2></section>',
 matchMedia:()=>({matches:mobile})
}
runInNewContext(graphicsFixture(source)+source.slice(source.indexOf('const SOLO_STUDIO_PROCESS='),source.indexOf('const DUO_STUDIO_PROCESS=')),scope)
runInNewContext(source.slice(source.indexOf('function detailStudioSteps('),source.indexOf('function processStudioMeta(')),scope)
runInNewContext(source.slice(source.indexOf('function wistiaBeforeAfterSection('),source.indexOf('function setExpertPanel(')),scope)
runInNewContext(source.slice(source.indexOf('function detailPointSection('),source.indexOf('function filmCommerceDetail(')),scope)
runInNewContext(source.slice(source.indexOf('function arRecordingPoster('),source.indexOf('function initArCommerceDetail(')),scope)
const desktop=scope.arCommerceDetail(scope.PRODUCTS.solo),duet=scope.arCommerceDetail(scope.PRODUCTS.duo,'duo')
mobile=true
const html=scope.arCommerceDetail(scope.PRODUCTS.solo)
assert.match(html,/mobile-ar-solo/)
const duetMobile=scope.arCommerceDetail(scope.PRODUCTS.duo,'duo')
assert.match(duetMobile,/mobile-ar-solo/)
assert.equal(duetMobile,duet,'DUET uses the same approved composition at every width')
assert.match(duetMobile,/data-ar-product="duo"/)
assert.match(duetMobile,/DUET · 2인/)
assert.match(duetMobile,/duo-wedding-song-ar\.mp4/)
assert.match(duetMobile,/href="\/event\/duo"/)
assert.match(duetMobile,/할인·페이백 모두 적용 후 혜택가<\/span><strong>80,000원/)
mobile=false
assert.equal(scope.arCommerceDetail(scope.PRODUCTS.solo),html,'SOLO PC and mobile markup match')
assert.equal(scope.arCommerceDetail(scope.PRODUCTS.duo,'duo'),duetMobile,'DUET PC and mobile markup match')
assert.match(desktop,/mobile-ar-solo/)
assert.match(desktop,/mas-bottom/)
for(const id of ['arcProductTitle','arcDetails','arcRecording','arcKey','reviews','arcFaq','arcProcess','wistiaBeforeAfter','wistiaBeforeAfterTitle','arRatioExperience'])assert.equal((html.match(new RegExp('id="'+id+'"','g'))||[]).length,1,id)
assert.equal((html.match(/<h1 /g)||[]).length,1)
assert.deepEqual([...html.matchAll(/detail-point-label"[^>]*>(POINT \d{2})</g)].map(m=>m[1]),['POINT 01','POINT 02','POINT 03','POINT 04','POINT 05'])
assert.ok(html.indexOf('mas-gallery')<html.indexOf('mas-summary'))
const intro=html.slice(html.indexOf('<section class="mas-intro"'),html.indexOf('<section class="mas-selection"'))
assert.match(intro,/aria-labelledby="arcProductTitle"/)
assert.match(intro,/mas-format-badge/)
assert.match(intro,/<div class="mas-brand">/)
assert.doesNotMatch(intro,/<a class="mas-brand"|class="mas-brand"[^>]*href=/)
assert.ok(intro.indexOf('mas-brand')<intro.indexOf('<h1'))
assert.match(intro,/class="mas-gallery-caption">위스티아와 함께 준비한 실제 본식 축가/)
assert.match(intro,/class="mas-gallery-track"/)
assert.match(intro,/class="mas-gallery-dots"/)
assert.match(intro,/data-mobile-video-slide="0"/)
assert.match(intro,/data-mobile-video-slide="1"/)
assert.equal((intro.match(/class="arc-product-media ar-hook-media mas-video-surface"/g)||[]).length,2)
assert.equal((intro.match(/data-ar-video-toggle aria-label="영상 재생"/g)||[]).length,2)
assert.match(css,/\.mas-video-surface \.ar-hook-video-control\{inset:0;/)
assert.match(css,/\[data-feedback="play"\] \.ar-icon-play/)
assert.match(css,/\[data-feedback="pause"\] \.ar-icon-pause/)
assert.match(source,/flashMobileArVideoFeedback\(el,'play'\)/)
assert.match(source,/flashMobileArVideoFeedback\(el,'pause'\)/)
assert.doesNotMatch(intro,/mas-evidence|상품상세|실제 후기 보기/)
assert.match(css,/\.mas-intro \.mas-summary h1\{text-align:left!important/)
assert.match(css,/\.mas-intro \.arc-product-media\{aspect-ratio:1\/1/)
assert.match(css,/object-fit:cover!important;object-position:50% 46%!important/)
assert.doesNotMatch(intro,/별점|구매 1위|만명/)
assert.ok(html.indexOf('mas-information')<html.indexOf('POINT 01'))
assert.ok(html.indexOf('mas-information')<html.indexOf('id="reviews"'))
assert.ok(html.indexOf('id="reviews"')<html.indexOf('POINT 01'))
assert.doesNotMatch(html,/mas-detail-cover|마음은 직접 전하고/)
assert.match(html,/<dt>녹음시간<\/dt>/)
assert.match(html,/<dt>포함 작업<\/dt><dd>녹음 · 보컬 디렉팅 · 음정·박자 보정 · 믹싱 · 마스터링<\/dd>/)
assert.match(html,/<dt>제작 기간<\/dt><dd>녹음 후 최대 7일 이내<\/dd>/)
assert.match(html,/<section class="arc-section arc-process mas-detailed-process story-process-cards" id="arcProcess"><h2>진행 순서<\/h2><details class="story-process-folder" open>/)
assert.equal((html.match(/class="story-process-card"/g)||[]).length,7)
assert.doesNotMatch(html,/준비부터 전달까지<br>이렇게 진행합니다/)
assert.match(css,/\.wistia-advantages li[^}]*text-align:left!important/)
assert.match(css,/\.ar-expert-panel-sub\{white-space:nowrap/)
assert.match(css,/\.arc-faq \.faq-list details\{box-sizing:border-box;width:100%;margin-inline:0;padding-inline:16px/)
assert.match(css,/\.arc-notices h2\{text-align:center!important/)
assert.match(css,/\.mas-location \.arc-location-link\{display:flex;[^}]*min-height:48px/)
assert.doesNotMatch(html,/<nav class="arc-tabs"/)
assert.doesNotMatch(desktop,/<nav class="arc-tabs"/)
assert.doesNotMatch(html,/가사 영상 옵션 견적 뽑기/)
assert.doesNotMatch(desktop,/가사 영상 옵션 견적 뽑기/)
assert.doesNotMatch(html,/<span data-solo-kicker>고객 후기|직접 보내주신 카카오톡 후기 원문입니다/)
assert.match(html,/<section class="arc-section arc-notices mas-notices">/)
assert.match(html,/<strong>납기<\/strong><div><b>최대 7일 이내<\/b><small>녹음 후/)
for(const term of ['3회까지 무료','4회차부터 회당 1만원'])assert.ok(html.includes(term),term)
assert.doesNotMatch(html,/빠른 작업|3일 이내|\+3만원/,'removed rush option does not appear in the mobile booking notice')
assert.doesNotMatch(desktop,/빠른 작업|3일 이내|\+3만원/,'removed rush option does not appear in the unified desktop notice')
assert.doesNotMatch(html,/mas-notice-options/)
assert.match(html,/가사 영상 제작 필요하신가요\?/)
assert.match(html,/보정·믹싱의 마법, 티 나지 않게 자연스럽게/)
assert.match(source,/준비부터 완성까지, 필요한 작업에 집중합니다/)
assert.doesNotMatch(html,/본식 전 재생·리허설 확인|mas-venue-note/)
assert.match(css,/\.arc-notices\{text-align:left!important/)
assert.match(css,/\.mas-notices li\{display:grid;grid-template-columns:60px minmax\(0,1fr\)/)
assert.match(html,/mas-cut-seam/)
assert.match(html,/좋은 구간을 이어 붙여요/)
assert.doesNotMatch(html,/arc-recording-photos/)
assert.match(html,/process-no-people\/03\.svg/)
assert.doesNotMatch(desktop,/arc-recording-photos/)
assert.match(desktop,/process-no-people\/03\.svg/)
assert.doesNotMatch(html,/key-typography-v1\.png/)
assert.match(html,/mas-key-editorial/)
assert.match(html,/음원 편집 · 키 조절 무료/)
assert.match(html,/mas-location/)
assert.match(html,/석천로170번길 19 <span>2층/)
assert.match(html,/부천시청역 1번 출구/)
assert.match(html,/주차 요금 별도 · 주차비 지원 불가/)
assert.match(html,/https:\/\/map.naver.com\/p\/search\//)
assert.match(html,/https:\/\/map.kakao.com\/link\/search\//)
assert.doesNotMatch(html,/지도·방문 안내 보기/)
assert.match(source,/mas-footer-slogan">완성도는 높이고, 부담은 줄인 가격을 약속드립니다/)
assert.match(source,/mobileTrack\.addEventListener\('mouseenter',pause\)/)
assert.match(source,/mobileTrack\.addEventListener\('touchstart',pause/)
assert.match(html,/href="\/detail\/duo"/)
assert.match(source,/el\.matches\("\.mobile-ar-solo \.mas-selection \.mas-variant"\)\?"\.mobile-ar-solo \.mas-selection"/)
assert.match(html,/120,000원/);assert.match(html,/160,000원/)
assert.match(html,/할인·페이백 모두 적용 후 혜택가<\/span><strong>40,000원/)
assert.match(html,/\(1곡 · 1인 · 1시간\)/)
assert.doesNotMatch(html,/data-quick-estimate|빠른 견적/)
assert.match(html,/href="\/event\/solo">카카오톡 문의/)
assert.doesNotMatch(html,/장바구니|바로구매|별점|구매 1위|arc-bottom|arc-time-guide|arc-empathy|arc-package|mas-benefits|경기도 부천 스튜디오 · 오시는 길/)
for(const path of [...html.matchAll(/(?:src|poster)="(assets\/[^"]+)"/g)].map(m=>m[1]))assert.ok(existsSync(new URL('../'+path,import.meta.url)),path)
assert.equal((html.match(/<video /g)||[]).length,2)
assert.equal((duetMobile.match(/<video /g)||[]).length,2)
assert.match(source,/function initMobileArGallery\(\)/)
assert.match(html,/groom-wedding-song-ar\.mp4/)
assert.match(html,/duo-wedding-song-ar\.mp4/)
assert.ok(css.trim().startsWith('/* Approved SOLO'))
assert.match(css,/@media \(min-width:0px\)/)
assert.match(css,/@media \(min-width:769px\)/)
assert.match(css,/body:has\(#app \.mobile-ar-solo\) #floatingKakao/)
assert.match(css,/safe-area-inset-bottom/)
assert.match(css,/menu-open,\.modal-open/)
assert.doesNotMatch(source,/soloMobileViewport|mobile boundary/,'resizing must not rebuild a detail page')
assert.doesNotMatch(source,/WistiaMobileSolo\?\./)
assert.doesNotMatch(shell,/src="js\/mobile-ar-solo\.js/)
assert.match(css,/arc-recording-flow svg\{[^}]*margin:8px auto 0/)
assert.match(css,/ar-story-intro \.solo-type-line[^}]*text-align:center!important/)
assert.match(home,/@media\(max-width:768px\)/)
assert.match(home,/text-align:center!important/)
assert.doesNotMatch(home,/font-size:|padding:|aspect-ratio:|grid-template-columns:|#floatingKakao|display:block.*we-service/,'alignment stylesheet must not redesign cards or actions')
assert.match(css,/mas-information dl>div\{display:grid;grid-template-columns:82px 1fr/)
assert.match(css,/\.mas-information dl>div\{grid-template-columns:minmax\(0,1fr\);gap:4px/)
assert.doesNotMatch(css,/mas-information dl>div\{grid-template-columns:1fr|mas-price\{flex-direction:column|mas-variant i\{position:absolute/)
assert.match(shell,/mobile-studio-home\.css\?v=20261003-alignment-only-1/)
console.log('SOLO and DUET mobile design, square videos, cut/join diagram, typography asset, notices, directions and existing actions passed')
