import assert from 'node:assert/strict'
import {readFileSync,existsSync} from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const index=read('index.html'),css=read('css/question-cards-kakao.css')
assert.ok(index.indexOf('css/question-cards-kakao.css')<index.indexOf('</head>'))
assert.ok(index.indexOf('css/question-cards-kakao.css')>index.indexOf('css/inquiry-actions.css'))
const chat=index.match(/<a[^>]+id="floatingKakaoChat"[^>]*>[\s\S]*?<\/a>/)[0]
assert.match(chat,/aria-label="카카오톡 문의"/)
assert.match(chat,/href="https:\/\/pf.kakao.com\/_GbExjX\/chat"/)
assert.match(chat,/target="_blank" rel="noopener noreferrer"/)
assert.match(chat,/class="floating-kakao-pill"/)
assert.match(chat,/<svg class="kakao-bubble"/)
assert.match(chat,/<span>카카오톡 문의<\/span>/)
assert.doesNotMatch(index,/id="floatingKakao"|id="soloDesktopCta"/)
assert.ok(existsSync(new URL('../assets/img/kakao-talk.png',import.meta.url)),'original PNG is preserved')
const svg=read('assets/img/interface/kakao-talk.svg')
assert.match(svg,/<svg[^>]+viewBox="0 0 630 630"/)
assert.match(svg,/<path/)
assert.doesNotMatch(svg,/<image|<text|data:image/)
assert.match(css,/\.consultation-fields\{padding:0!important;border:0;background:transparent!important/)
assert.match(css,/\.consultation-field-grid>\.contact-field\{[^}]+border:1px solid #dfe4e8[^}]+background:#fff/)
assert.match(css,/grid-template-columns:minmax\(0,1fr\);gap:16px/)
assert.match(css,/font-size:16px/)
assert.match(css,/\.contact-field>legend\{float:left/)
assert.match(css,/\.contact-time-selects \.sr-only\{position:absolute;width:1px;height:1px/)
assert.match(css,/:has\(\[aria-invalid="true"\]\)/)
assert.match(css,/width:56px!important;height:56px!important;min-height:56px!important/)
assert.match(css,/safe-area-inset-bottom/)
assert.match(css,/focus-visible/)
assert.match(css,/prefers-reduced-motion:reduce/)
console.log('Separate question cards, accessible native controls and icon-only Kakao link passed')
