import assert from 'node:assert/strict'
import {graphicsFixture} from './studio-graphics-fixture.mjs'
import {readFileSync,existsSync} from 'node:fs'
import {runInNewContext} from 'node:vm'
const read=file=>readFileSync(new URL('../'+file,import.meta.url),'utf8')
const app=read('js/app.js'),css=read('css/responsive-pages.css')
const fn=app.slice(app.indexOf('function storyProcessCards('),app.indexOf('function verticalProcessSection('))
const scope={img:(src,alt)=>`<img src="${src}" alt="${alt}">`,escapeHtml:x=>x}
runInNewContext(graphicsFixture(app)+fn,scope)
const markup=scope.storyProcessCards(Array.from({length:7},()=>({})))
assert.equal((markup.match(/<img /g)||[]).length,9,'one decorative 3D folder plus all eight actual stage images')
assert.equal((markup.match(/<li class="story-process-card"/g)||[]).length,8)
const storyMedia=[...markup.matchAll(/<div class="story-process-media"><img src="([^"]+)" alt="([^"]+)"/g)]
assert.equal(storyMedia.length,8,'decorative folder must not count as or replace a production stage')
assert.ok(storyMedia.every(([,src,alt])=>src&&alt),'all story production stages retain meaningful media')
assert.deepEqual([...markup.matchAll(/<h3>([^<]+)<\/h3>/g)].map(m=>m[1]),['곡·파트 상담','구간별 녹음','축가 영상 촬영','수작업 보컬 보정','믹싱·마스터링','영상 편집','최종 검수','완성본 전달'])
assert.match(markup,/src="assets\/img\/duet-film\/duet-recording\.webp"/,'real filming image stays in stage three')
assert.match(markup,/src="assets\/img\/song-film\/duet-video-cover\.jpg"/,'real finished video stays in stage eight')
assert.match(markup,/촬영·자료 전달 후 약 14일/)
assert.match(markup,/studio-folder-art studio-folder-3d" aria-hidden="true"><img[^>]*alt=""/,'new decorative folder is hidden only from assistive reading')
assert.match(markup,/<details class="story-process-folder" open><summary>/)
assert.match(markup,/제작 과정 살펴보기/)
assert.match(markup,/--process-index:2;--process-row:2;--process-column:1/)
assert.match(markup,/--process-index:3;--process-row:2;--process-column:2/)
assert.match(markup,/class="process-flow"/)
assert.doesNotMatch(markup,/story-process-arrow/)
assert.match(css,/body\{--app-canvas-width:1280px\}/)
assert.match(css,/:root\{--page-gutter:20px;--page-gap:40px\}/)
assert.match(css,/prefers-reduced-motion:reduce/)
assert.match(css,/story-process-folder\[open\] .story-process-card\{animation:none/)
assert.match(app,/\['진행 안내','\/info\/process'\]/)
assert.match(app,/renderBeforeAfterPage\(\)/)
assert.match(app,/setAttribute\("aria-expanded","false"\);document.querySelector\("#menuToggle"\)\?\.setAttribute\("aria-label","메뉴 열기"\)/)
assert.match(app,/wistia-directions\.png/)
assert.ok(existsSync(new URL('../assets/img/wistia-directions.png',import.meta.url)))
runInNewContext(app.slice(app.indexOf('const SOLO_STUDIO_PROCESS='),app.indexOf('const DUO_STUDIO_PROCESS=')),scope)
runInNewContext(app.slice(app.indexOf('function detailStudioSteps('),app.indexOf('function processStudioMeta(')),scope)
runInNewContext(app.slice(app.indexOf('function mobileArProcess('),app.indexOf('function mobileArNotices(')),scope)
for(const key of ['solo','duo']){
 const ar=scope.mobileArProcess(key)
 assert.equal((ar.match(/<li class="story-process-card"/g)||[]).length,7,key+' keeps every approved AR stage')
 assert.equal((ar.match(/<div class="story-process-media"><img /g)||[]).length,7,key+' keeps seven genuine explanatory stage images')
 assert.deepEqual([...ar.matchAll(/class="story-process-number">(\d{2})</g)].map(m=>m[1]),['01','02','03','04','05','06','07'])
 assert.match(ar,/<details class="story-process-folder" open>/)
 assert.match(ar,/최종 검수 · 전달/)
 assert.match(ar,/본식에서 바로 사용할 수 있도록/)
}
for(const [,src] of markup.matchAll(/src="([^"]+)"/g))assert.ok(existsSync(new URL('../'+src,import.meta.url)),src)
console.log('Decorative 3D folder separated from eight story/seven AR stages, shared responsive pages and supplied map: passed')
