import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const css=read('css/studio-editorial.css'),source=read('js/app.js'),index=read('index.html')
assert.match(index,/data-wistia-typography="pretendard-editorial"/)
assert.match(index,/studio-editorial.css\?v=20261006-studio-editorial-1/)
assert.doesNotMatch(index,/maru-buri.css/)
assert.match(source,/studio-home-hero/)
assert.match(source,/studio-hero-media/)
assert.match(source,/studio-hero-actions/)
assert.match(source,/img\('assets\/img\/hero\/wistia-hero-main.webp','[^']+',true\)/)
assert.match(css,/\.studio-hero-actions a:first-child \*\{[^}]*color:#FFFFFF!important/)
assert.match(css,/\.story-process-grid \.story-process-card\{[^}]*border-bottom:1px solid #E8E8E8/)
assert.match(css,/\.mas-story-chapters ol\{grid-template-columns:1fr/)
assert.match(css,/\.faq-list summary\{[^}]*font-size:15px/)
assert.match(css,/\.consultation-flow :is\(input[^}]*font-size:16px!important/)
assert.match(css,/\.booking-calculator-wrap.consultation-flow\{background:transparent!important/)
assert.match(css,/#floatingKakao#floatingKakao\{[^}]*right:20px!important/)
assert.match(css,/:focus-visible/)
assert.match(css,/@media\(prefers-reduced-motion:no-preference\)/)
assert.doesNotMatch(css,/display:none|pointer-events:none|filter:|visibility:hidden/)
for(const route of ['detail/solo','detail/duo','detail/duet-film','contact','event/solo','event/duo','event/duet-film','info/about','info/faq','info/process','info/location','events','song','film','ar/self','ar/friend','before-after']) assert.match(read(route+'.html'),/studio-editorial.css/)
assert.match(read('privacy.html'),/studio-editorial.css/)
for(const route of ['find/role','find/service','find/people']) {
 assert.match(read(route+'.html'),/studio-editorial.css/)
 assert.match(read(route+'.html'),/name="robots" content="noindex, follow"/)
}
assert.match(source,/story-process-folder home-process-folder" open/)
assert.match(source,/function mobileArProcess\(key="solo"\)\{\s*const steps=detailStudioSteps\(key\)/)
assert.match(source,/완성도는 높이고, 부담은 줄인 가격을 약속드립니다/)
console.log('Studio editorial: readable sans typography, media-led home, intact folders, utility pages and inquiry affordances passed')
