import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8')
const css=read('css/dusty-wedding-theme.css'),app=read('js/app.js')
assert.match(css,/\.mas-selection \.mas-variant\{padding:18px 16px!important;gap:12px/)
assert.match(css,/\.mas-selection \.mas-variant>small\{flex:0 0 auto;white-space:nowrap;padding-inline:2px/)
assert.match(css,/\.mas-variant\+\.mas-variant\{margin-top:12px/)
assert.match(css,/@media\(min-width:769px\)[^\n]+\.mas-variant\+\.mas-variant\{margin-top:0/)
assert.match(css,/\.mas-gallery\[data-mobile-gallery\] \.mas-gallery-caption\{position:absolute;z-index:2;top:12px;left:12px/)
assert.match(css,/max-width:calc\(100% - 80px\)/)
assert.match(css,/\.mas-cut-clips>div\{background:var\(--dusty-pink\)/)
assert.match(css,/\.mas-cut-clips>div:last-child\{background:var\(--warm-beige\)/)
assert.match(css,/\.mas-joined-clip\{background:linear-gradient\(90deg,var\(--dusty-pink\) 50%,var\(--warm-beige\) 50%\)/)
assert.match(css,/\.mas-joined-clip>div:last-child\{color:var\(--warm-brown\)/)
assert.match(app,/showKakaoInquiryDialog/)
assert.match(app,/contactValidationForm/)
assert.match(read('js/contact-form.js'),/이제 복사하고 카카오톡으로!'/)
for(const route of ['','contact','detail/solo','detail/duo','detail/duet-film'])assert.match(read(route?route+'.html':'index.html'),/dusty-wedding-theme.css\?v=20261005-monochrome-maru-1/)
console.log('Media caption, selection gutters, two-clip diagram mapping and existing inquiry flow preserved')
